# Base configs
baseurl: "https://catzwu.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Catherine Wu Photography"
subtitle: "See the world through my eyes!"
author: "Ram"
header:
 title: "Photography"
 subtitle: "by Catherine Wu"
footer:
 name: "Hey there, I'm Catherine"
 bio: "I am a student, most recently of photography."
web_design: "AJ"
