# Base configs
baseurl: "https://catzwu.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Catherine Wu"
subtitle: "See the world through my eyes!"
author: "Catherine Wu"
header:
 title: "Photography"
 subtitle: "by Catherine Wu"
footer:
 name: "Hey there, I'm Catherine"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
