# Base configs
baseurl: "https://catzwu.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Catherine"
subtitle: "See the world through my eyes!"
author: "Ram"
header:
 title: "Photography"
 subtitle: "by Catherine"
footer:
 name: "Hey there, I'm Catherine"
 bio: "Thinker, scientist, amateur photographer, with an affinity for cats."
web_design: "AJ"
